### ISSUE TITLE
Problem with the script after update OpenWebRX+  to 1.2.54 version

### ISSUE THREAD

**Issue by Rs20232023** [kam821/openwebrxplus-superpower#1]
Hi,
Many thanks for your script! The script worked very well for me, but after updating OpenWebRX+ to the version 1.2.54 one of the script options stopped working. After updating manual frequency shifting (by step) does not work. The frequency does not change after manually entering the value. Please check it.
My system:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by kam821** [comment]
It should work now in 0.1.8
Newer versions of OpenWebRX+ put some weird values in settings form, so a proper rework is required, but temporarly a workaround was introduced.
I would like to ask for feedback if everything is ok.

**Comment by Rs20232023** [comment]
> It should work now in 0.1.8 Newer versions of OpenWebRX+ put some weird values in settings form, so a proper rework is required, but temporarly a workaround was introduced. I would like to ask for feedback if everything is ok.

The fix works!
Thank you very much!
